### ISSUE TITLE
ImportError: No module named termios fro window 8

### ISSUE THREAD

**Issue by pawanpanchal2017** [nu774/sudo-for-cygwin#10]
c:\>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\netmiko\__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "c:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 4, in <mo
dule>
    from netmiko.a10 import A10SSH
  File "c:\Python27\lib\site-packages\netmiko\a10\__init__.py", line 2, in <modu
le>
    from netmiko.a10.a10_ssh import A10SSH
  File "c:\Python27\lib\site-packages\netmiko\a10\a10_ssh.py", line 4, in <modul
e>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "c:\Python27\lib\site-packages\netmiko\cisco_base_connection.py", line 3,
 in <module>
    from netmiko.base_connection import BaseConnection
  File "c:\Python27\lib\site-packages\netmiko\base_connection.py", line 24, in <
module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured
_data
  File "c:\Python27\lib\site-packages\netmiko\utilities.py", line 9, in <module>

    import clitable
  File "c:\Python27\lib\site-packages\clitable.py", line 34, in <module>
    import texttable
  File "c:\Python27\lib\site-packages\texttable.py", line 34, in <module>
    import terminal
  File "c:\Python27\lib\site-packages\terminal.py", line 34, in <module>
    import termios
ImportError: No module named termios

**Comment by hossemtamsouh** [comment]
i had this error can you help me...and thanks
![Uploading ScreenShot_20201023230734.png…]()
