### ISSUE TITLE
importing `fcntl` and `termios` 

### ISSUE THREAD

**Issue by jacob-roth** [nu774/sudo-for-cygwin#8]
Hi, I'm having issues with steps 8 & 9. When I run `$ python sudoserver.py` from Cygwin after navigating to its location, I receive the following error message:

> Traceback (most recent call last):
>   File "sudoserver.py", line 4, in <module>
>     import fcntl
> ImportError: No module named fcntl

Is this something I've done wrong? I'm running Windows 7. Thanks!

**Comment by JerellDR** [comment]
I'm having the same issue on win 10. I did a little bit of research and found [this stackoverflow post](https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl) that suggests the fcntl module is not available on windows.

**Comment by nu774** [comment]
Well I've already abandoned this project, but I guess you guys are just not running Cygwin python.
Try running:
```python -c "import sys; print(sys.platform)"```
If it is Cygwin python, it will say "cygwin". Otherwise you will get "win32".

**Comment by pawanpanchal2017** [comment]
Hi Experts,

i am having below error while installing the netmiko
Can you please help me ?

c:\>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\netmiko\__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "c:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 4, in <mo
dule>
    from netmiko.a10 import A10SSH
  File "c:\Python27\lib\site-packages\netmiko\a10\__init__.py", line 2, in <modu
le>
    from netmiko.a10.a10_ssh import A10SSH
  File "c:\Python27\lib\site-packages\netmiko\a10\a10_ssh.py", line 4, in <modul
e>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "c:\Python27\lib\site-packages\netmiko\cisco_base_connection.py", line 3,
 in <module>
    from netmiko.base_connection import BaseConnection
  File "c:\Python27\lib\site-packages\netmiko\base_connection.py", line 24, in <
module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured
_data
  File "c:\Python27\lib\site-packages\netmiko\utilities.py", line 9, in <module>

    import clitable
  File "c:\Python27\lib\site-packages\clitable.py", line 34, in <module>
    import texttable
  File "c:\Python27\lib\site-packages\texttable.py", line 34, in <module>
    import terminal
  File "c:\Python27\lib\site-packages\terminal.py", line 34, in <module>
    import termios
ImportError: No module named termios
